dist: trusty
addons:
  chrome: stable

notifications:
  email: false

sudo: false
language: ruby
cache: bundler

rvm:
  - 2.4.1

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
