EDS_QUERY_API_URL: 'http://localhost:3000/articles?q=%{q}&rows=%{max}&format=json'
EDS_QUERY_URL: 'http://localhost:3000/articles?q=%{q}'
EDS_FETCH_URL: 'http://localhost:3000/articles/%{id}'
CATALOG_QUERY_API_URL: 'http://localhost:3000/?q=%{q}&rows=%{max}&format=json'
CATALOG_QUERY_URL: 'http://localhost:3000/?q=%{q}'
CATALOG_FETCH_URL: 'http://localhost:3000/view/%{id}'
MAX_RESULTS: 3
CATALOG_HOME_URL: 'https://searchworks.stanford.edu'
ARTICLES_HOME_URL: 'https://searchworks.stanford.edu/articles'
LIBRARY_WEBSITE_HOME_URL: 'https://library.stanford.edu'
YEWNO_HOME_URL: 'https://yewno.com/edu'
